import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Suspense } from 'react';
import AppWrapper from '@/components/wrapper/appWrapper';
import { ToastContainer } from 'react-toastify';
import Loading from '@/components/loading/Loading';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper>
          <Suspense fallback={<Loading />}>
            <Header />
            {children}
            <Footer />
            <ToastContainer
              position="top-right"
              autoClose={5000}
              closeOnClick
            />
          </Suspense>
        </AppWrapper>
      </body>
    </html>
  );
}
