import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AppWrapper from '@/components/wrapper/appWrapper';
import { ToastContainer } from 'react-toastify';
import ContentWrapper from '@/components/wrapper/contentWrapper';
import { Sidebar } from '@/components/Sidebar';
import Header from '@/components/Header';
import StoreProvider from '@/components/miscellaneous/storeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AppWrapper>
            <Sidebar />
            <ContentWrapper>
              <Header />
              {children}
            </ContentWrapper>
            <ToastContainer
              position="top-right"
              autoClose={5000}
              closeOnClick
            />
          </AppWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
